### PR TITLE
fix and add sources

### LINKED ISSUE #48: MangaOwl Changed Their Domain
### Source name

MangaOwl

### Source link

https://mangaowl.to/manga

### Language

English

### Other details

MangaOwl changed their domain recently, so please update MangaOwl in the app to reflect it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

### LINKED ISSUE #76: Add new source: Dynasty Reader
### Source name

Dynasty Reader

### Source link

https://dynasty-scans.com/

### Language

English

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

### LINKED ISSUE #136: Bakai (Portuguese Lewd Source)
### Source name

Bakai

### Source link

https://bakai.org

### Language

Portuguese

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

### LINKED ISSUE #224: Request: GourmetScans
### Source name

GourmetScans & Daddies Supremacy

### Source link

https://gourmetscans.net

### Language

English

### Other details

Indonesian language is also available in a separate domain.

Site is Madara based. Sample code:
```Kotlin
@MangaSourceParser("GOURMETSCANS", "Gourmet Scans & Daddies Supremacy", "en")
internal class GourmetScans(context: MangaLoaderContext) :
    MadaraParser(context, MangaSource.GOURMETSCANS, "gourmetscans.net") {

    override val tagPrefix = "genre/"
}
```

I tried to implement it myself but it's unable to find the `chapter-data-protector` script.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

### PR DESCRIPTION
**Pull request by davvarrr**
fix and add sources

fix : 
fix tag on madara template
fix 2nd page chapter on bentomanga
fix templescan.net move to no template
add logique src() to mangareader template
and other minor fix 

sources : 

-remove : mangabilgini.com site close

dynasty-scans.com -> close #76 
mangaowl.to -> close #48 
furyosociety.com
bestmanhua.com
doujinhentai.net
gourmetscans.net -> close #224 
id.gourmetscans.net
wickedwitchscan.com
www.pantheon-scan.fr
komiksan.link
sssscanlator.com
frscans.com
bakai.org -> close #136 
goldenmanga.top
peacescans.com

ps :
some issues need to close check -> #221 , #140 , #89 , #68 ,

### CODE REVIEW

File: src/main/kotlin/org/koitharu/kotatsu/parsers/site/en/DynastyScans.kt [hunk 1]
```diff
@@ -0,0 +1,172 @@
...
+			description = null,
+			chapters = chapters,
+		)
+	}
+
+	private fun getChapters(doc: Document): List<MangaChapter> {
+		val dateFormat = SimpleDateFormat("MMM dd yy", sourceLocale)
+		return doc.body().select("dl.chapter-list dd").mapChapters { i, li ->
+			val a = li.selectFirstOrThrow("a")
+			val href = a.attrAsRelativeUrlOrNull("href") ?: li.parseFailed("Link is missing")
```
Comment (Koitharu) [inline src/main/kotlin/org/koitharu/kotatsu/parsers/site/en/DynastyScans.kt:137]:
```suggestion
			val href = a.attrAsRelativeUrl("href")
```
