### PR TITLE
add sources and fix

### LINKED ISSUE #132: imhentai.xxx [English]
### Source name

MReader, IMHentai

### Source link

https://imhentai.xxx/

### Language

English

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

### LINKED ISSUE #165: New source: pururin.to
### Describe your suggested feature
Please add a rich NSFW source:
[pururin.to](https://pururin.to/)

### Acknowledgements
- [x] I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open issue.

### LINKED ISSUE #253: FlixScans and ManjaNoon : (Source request)
### Source name

FlixScans and Manjanoon

### Source link

https://flixscans.com/webtoons/home
and
https://manjanoon.com/webtoons/home

### Language

Arabic

### Other details

Galaxy Manga is no longer working other than its link to this link

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

### LINKED ISSUE #262: hentaifox (Source Request)
### Source name

Hentaifox

### Source link

https://hentaifox.com/

### Language

Multi

### Other details

This source has multiple languages
https://hentaifox.com/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

### LINKED ISSUE #264: Request new source for vietnamese
### Source name

TruyenQQ

### Source link

https://truyenqqq.vn/

### Language

Vietnamese

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

### LINKED ISSUE #284: [Komikcast] Wrong navigation
### Source information

Komikcast

### Steps to reproduce

1. Explore -> komikcast
2. Sorting Order -> updated
3. 
Screenshot_2023-10-09-15-44-21-129_org koitharu kotatsu

### Kotatsu version

6.1.6

### Android version

12

### Other details

It not an updated manga list
Please see the video below :

https://github.com/KotatsuApp/kotatsu-parsers/assets/45929526/4d22cc08-5c14-45fa-bdc6-a90642c2b7cd

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

### LINKED ISSUE #290: MANGA AY
### Source name

Manga Ay

### Source link

https://manga-ay.com/

### Language

Turkish 

### Other details

18+/NSFW: YES

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

### LINKED ISSUE #292: Yaoiflix
### Source name

Yaoiflix 

### Source link

https://www.yaoiflix.info/

### Language

Turkish 

### Other details

18+/NSFW: YES 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

### LINKED ISSUE #293: Domal Fansub
### Source name

Domal Fansub 

### Source link

https://domalfansb.com/

### Language

Turkish 

### Other details

18+/NSFW: YES

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

### LINKED ISSUE #294: Hoi Fansub
### Source name

Hoi Fansub 

### Source link

https://hoifansub.com/

### Language

Turkish 

### Other details

18+/NSFW: YES

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

### LINKED ISSUE #300: Ler Manga Online
### Source name

Ler Manga Online

### Source link

https://lermangaonline.com.br/

### Language

Brazilian Portuguese

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

### LINKED ISSUE #301: Manga Online
### Source name

Manga Online

### Source link

https://mangaonline.biz

### Language

Brazilian Portuguese

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

### LINKED ISSUE #302: only 2 pages load in Mangabuddy
### Source information

"MangaBuddy"

### Steps to reproduce

1. Add MangaBuddy source
2. Open any manga in the source
3. It will say only 2 pages are present

### Kotatsu version

"6.1.6"

### Android version

"Android 8.1"

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

### PR DESCRIPTION
**Pull request by davvarrr**
add RelatedManga on madara and mangareader template

New source :

mangastorm.org -> close #248 
flixscans.com -> close #253
hentaifox.com -> close #262
truyenqqvn.com -> close #264
pururin.to -> close #165
imhentai.xxx -> close #132 
sectscans.com
miraiscans.com
astrascans.com
domalfansb.com -> close #293 
hoifansub.com -> close #294 
mangatime.co
manhua-fenix.com
magusmanga.com
www.manhwaden.com
ladyestelarscan.com.br
passamaoscan.com
remangas.net
lermangaonline.com.br -> close #300 
mangaonline.biz -> close #301 
manga-ay.com -> close #290 
www.yaoiflix.info -> close #292 
limboscan.com.br

fix :
typo
Manga Buddy fix pages -> close #302 
komikcast -> close #284 
MmrcmsParser -> fixed search
aiyumanga.com -> aiyumanhua.com
fr-scan.cc
beast-scans.com -> beastscans.net
www.lelmanga.com
mangadistrict.com
lugnica-scans.com ( remove search )
manga-fr.me -> manga-fr.cc
scantrad-vf.co -> scantrad-vf.me
mangamanhua.online -> mangaonlineteam.com
mangalike.me -> manga-like.net
ozulscans.net -> ar-ozulscans.com
lugnicaScans
YugenMangas pt

### CODE REVIEW

File: src/main/kotlin/org/koitharu/kotatsu/parsers/site/vi/Truyenqq.kt [hunk 1]
```diff
@@ -0,0 +1,134 @@
...
+	override suspend fun getListPage(
+		page: Int,
+		query: String?,
+		tags: Set<MangaTag>?,
+		sortOrder: SortOrder,
+	): List<Manga> {
+		val tagQuery = if (tags.isNullOrEmpty()) "" else tags.joinToString(separator = ",") { it.key }
+		val url = if (!query.isNullOrEmpty()) {
+			buildString {
+				append("https://$domain")
```
Comment (Koitharu) [inline src/main/kotlin/org/koitharu/kotatsu/parsers/site/vi/Truyenqq.kt:27]:
```suggestion
				append("https://")
				append(domain)
```

File: src/main/kotlin/org/koitharu/kotatsu/parsers/site/vi/Truyenqq.kt [hunk 2]
```diff
@@ -0,0 +1,134 @@
...
+				append("/tim-kiem/trang-$page.html")
+				append("?q=")
+				append(query.urlEncoded())
+			}
+		} else {
+			buildString {
+				append("https://$domain")
```
Comment (Koitharu) [inline src/main/kotlin/org/koitharu/kotatsu/parsers/site/vi/Truyenqq.kt:34]:
```suggestion
				append("https://")
				append(domain)
```

File: src/main/kotlin/org/koitharu/kotatsu/parsers/site/fr/LugnicaScans.kt [hunk 3]
```diff
@@ -49,6 +49,10 @@ internal class LugnicaScans(context: MangaLoaderContext) : PagedMangaParser(cont
 		sortOrder: SortOrder,
 	): List<Manga> {
 
+		if (!query.isNullOrEmpty()) {
+			return emptyList()
```
[the remark this answers is not in the document]
Comment (davvarrr) [reply src/main/kotlin/org/koitharu/kotatsu/parsers/site/fr/LugnicaScans.kt]: Indeed it will be clearer. ( perhaps put an exception so that it is not visible during a manga search on several sources )

**Comment by davvarrr** [comment]
info I set up a branch with the language of the manga to better identify it.
but since a commit on kotatsu the sources that I did like that no longer works (the chapter is no longer displayed)
source: hentaifox, imhentai and I can be others
(mangadex by default does not display chapters too)

**Comment by Koitharu** [comment]
List of branches is only visible when its count > 1

**Comment by davvarrr** [comment]
Ok so you have to remove the branch in hentaifox and imhentai to add them in the name ( lang - chapter name )
If not, the 2 sources won't work, they won't have a visible chapter 
If you could change it before updating the app, I'm not at home to do it.

**Comment by Koitharu** [comment]
I'll fix it on the app side
