### PR TITLE
fix title selector

### LINKED ISSUE #768: manga title not showing up
### Source information

ShibaManga

### Steps to reproduce

Hi i don't know if this is just for me or for more users, but some of my manga, in my library don't show the titles, what i found: the only common is that these titles are from ShibaManga.
Screenshot_20240518_103811_Kotatsu
Screenshot_20240518_103436_Kotatsu

### Kotatsu version

7.0.1

### Android version

Android 14

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

### PR DESCRIPTION
**Pull request by NagaYZ**
Closes #768

### CODE REVIEW

File: src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/en/ShibaManga.kt [hunk 1]
```diff
@@ -2,13 +2,57 @@ package org.koitharu.kotatsu.parsers.site.madara.en
...
+import org.jsoup.nodes.Document
+import org.koitharu.kotatsu.parsers.util.*
 
 @MangaSourceParser("SHIBAMANGA", "ShibaManga", "en")
 internal class ShibaManga(context: MangaLoaderContext) :
 	MadaraParser(context, MangaSource.SHIBAMANGA, "shibamanga.com") {
 
 	override val datePattern = "MM/dd/yyyy"
+	override fun parseMangaList(doc: Document): List<Manga> {
+		println(doc)
```
Comment (Koitharu) [inline src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/en/ShibaManga.kt:16]: Forgot to remove?

Comment (NagaYZ) [reply src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/en/ShibaManga.kt:16]: oh yes sorry
