### PR TITLE
adds sources and fix

### LINKED ISSUE #245: ComicArab (Source Request)
### Source name

ComicArab 

### Source link

https://comicarab.com/

### Language

Arabic

### Other details

nsfw +18

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

### LINKED ISSUE #246: SpiderScans (Source Request)
### Source name

SpiderScans

### Source link

https://spiderscans.com/

### Language

Arabic

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

### LINKED ISSUE #254: Galaxy Action : Source request)
### Source name

Galaxy Action

### Source link

https://galaxyaction.site/

### Language

Arabic

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

### PR DESCRIPTION
**Pull request by davvarrr**
New source :

manga.adonisfansub.com
akumanga.com
akumanotenshi.com
constellarcomic.com
cosmicscans.id
www.raindropteamfan.com
diskusscan.com
futari.info
comicarab.com
enryumanga.com
spiderscans.com -> close #246
lshistoria.com -> close #245
luminousscans.com
lyrascans.com
mangagenki.com
mangajp.top
miscans.my.id
arcurafansub.com
yumekomik.com
laviniafansub.com
titanmanga.com
nirvanamanga.com
sugarlab.my.id
shirakami.xyz
sirenkomik.my.id
toomtam-manga.coms
tumanhwas.com
galaxyaction.site -> close #254 
mangaxico.com
xcalibrscans.com
clover-manga.com
comicsvalley.com
komikto.com
ghostfansub.biz
freecomiconline.me
doujinza.com
en.huntersscan.xyz
huntersscan.xyz
www.instamanhwa.com
knightnoscanlation.com
manga18fx.com
lhtranslation.net
manhuauss.com
mangaeclipse.com
mangakik.biz
ww.mangalek.org
mangastarz.com
www.mangasy.com
mangawow.com
manhwa18.cc
www.kataitake.fr
manhwaraw.com
manytoon.club
www.porncomixonline.net
piedpiperfansub.me
reset-scans.com
reaperscanstr.com
strayfansub.homes
www.stickhorse.cl
setsuscans.com
tmomanga.com
www.toongod.org
topcomicporno.com
yanpfansub.com
manhuascan.io
scan-manga.me
www.anzmangashd.com
lector.pzykosis666hfansub.com
assortedscans.com
onma.me
adulto.seinagi.org.es
reader.seinagi.org.es

fix :

tecnoscann.com (  madra to mangareader )

url :

kanzenin.xyz -> kanzenin.info
aresmanga.org -> aresnov.org
komikcast.io -> komikcast.vip ( and fix select a )
komiktap.in -> 92.87.6.124
en.leviatanscans.com -> lscomic.com ( and rename )
vermanhwa.es -> vermanhwa.com
hayalistic.com  -> hayalistic.com.tr
webtoonhatti.com -> webtoonhatti.net
webtoon-tr.com  -> webtoontr.net
stmgs.com -> swatmanga.co

### CODE REVIEW

File: src/main/kotlin/org/koitharu/kotatsu/parsers/site/foolslide/en/AssortedScans.kt [hunk 1]
```diff
@@ -0,0 +1,141 @@
...
+		sortOrder: SortOrder,
+	): List<Manga> {
+
+		val doc = if (!query.isNullOrEmpty()) {
+
+			val url = buildString {
+				append("https://$domain/$searchUrl")
+				append("?q=")
+				append(query.urlEncoded())
+				if (page > 1) {
```
Comment (Koitharu) [inline src/main/kotlin/org/koitharu/kotatsu/parsers/site/foolslide/en/AssortedScans.kt:35]: This can be moved out of `buildString`

File: src/main/kotlin/org/koitharu/kotatsu/parsers/site/foolslide/en/AssortedScans.kt [hunk 2]
```diff
@@ -0,0 +1,141 @@
...
+		page: Int,
+		query: String?,
+		tags: Set<MangaTag>?,
+		sortOrder: SortOrder,
+	): List<Manga> {
+
+		val doc = if (!query.isNullOrEmpty()) {
+
+			val url = buildString {
+				append("https://$domain/$searchUrl")
```
Comment (Koitharu) [inline src/main/kotlin/org/koitharu/kotatsu/parsers/site/foolslide/en/AssortedScans.kt:32]: If you already use a `StringBuilder` it might be better to avoid concatenation

```suggestion
				append("https://")
				append(domain)
				append('/')
				append(searchUrl)
```

File: src/main/kotlin/org/koitharu/kotatsu/parsers/site/foolslide/en/AssortedScans.kt [hunk 3]
```diff
@@ -0,0 +1,141 @@
...
+			testAdultPage
+		}
+		val chapters = getChapters(manga, doc)
+
+		val desc = doc.getElementById("series-desc")?.selectFirst("div")?.html()
+		val alt = doc.getElementById("series-aliases")?.selectFirst("div.alias")?.text()
+		val author = doc.getElementById("series-authors")?.selectFirst("div.author")?.text()
+		val state = doc.getElementById("series-status")?.selectFirst("span")?.text()
+		manga.copy(
+			tags = emptySet(),
```
Comment (Koitharu) [inline src/main/kotlin/org/koitharu/kotatsu/parsers/site/foolslide/en/AssortedScans.kt:90]: Is it useful? I suppose we can keep the current `tags` value

File: src/main/kotlin/org/koitharu/kotatsu/parsers/site/foolslide/en/AssortedScans.kt [hunk 4]
```diff
@@ -0,0 +1,141 @@
...
+			coverUrl = doc.selectFirst(".cover")?.src().orEmpty(),// for manga result on search
```
Comment (Koitharu) [inline src/main/kotlin/org/koitharu/kotatsu/parsers/site/foolslide/en/AssortedScans.kt:91]:
```suggestion
			coverUrl = doc.selectFirst(".cover")?.src() ?: manga.coverUrl,
```

File: src/main/kotlin/org/koitharu/kotatsu/parsers/site/foolslide/en/AssortedScans.kt [hunk 5]
```diff
@@ -0,0 +1,141 @@
...
+	}
+
+	override suspend fun getPages(chapter: MangaChapter): List<MangaPage> {
+		val chapterUrl = chapter.url.toAbsoluteUrl(domain)
+		val docs = webClient.httpGet(chapterUrl).parseHtml()
+		val max = docs.selectFirstOrThrow(".curr-page input").attr("data-max").toInt() + 1
+		val pages = ArrayList<MangaPage>(max)
+		for (i in 1 until max) {
+			val pagesUrl = chapterUrl + i
+			val page = webClient.httpGet(pagesUrl).parseHtml().requireElementById("page-image").attr("src")
```
Comment (Koitharu) [inline src/main/kotlin/org/koitharu/kotatsu/parsers/site/foolslide/en/AssortedScans.kt:129]: It is better to move this request into `getPageUrl` method

File: src/main/kotlin/org/koitharu/kotatsu/parsers/site/foolslide/en/Seinagi.kt [hunk 6]
```diff
@@ -0,0 +1,51 @@
...
+			doc.selectFirstOrThrow(selectInfo).text()
+		}
+
+		val author = if (doc.selectFirstOrThrow(selectInfo).html().contains("Author")) {
+			doc.selectFirstOrThrow(selectInfo).text().substringAfter("Author: ").substringBefore("Art")
+		} else {
+			null
+		}
+
+		manga.copy(
```
Comment (Koitharu) [inline src/main/kotlin/org/koitharu/kotatsu/parsers/site/foolslide/en/Seinagi.kt:41]: Same remarks as below

File: src/main/kotlin/org/koitharu/kotatsu/parsers/site/foolslide/es/Pzykosis666hFansub.kt [hunk 7]
```diff
@@ -0,0 +1,49 @@
...
+			doc.selectFirstOrThrow(selectInfo).text()
+		}
+
+		val author = if (doc.selectFirstOrThrow(selectInfo).html().contains("Author")) {
+			doc.selectFirstOrThrow(selectInfo).text().substringAfter("Author: ").substringBefore("Art")
+		} else {
+			null
+		}
+
+		manga.copy(
```
Comment (Koitharu) [inline src/main/kotlin/org/koitharu/kotatsu/parsers/site/foolslide/es/Pzykosis666hFansub.kt:39]: Same

File: src/main/kotlin/org/koitharu/kotatsu/parsers/site/foolslide/es/SeinagiAdulto.kt [hunk 8]
```diff
@@ -0,0 +1,56 @@
...
+			doc.selectFirstOrThrow(selectInfo).text()
+		}
+
+		val author = if (doc.selectFirstOrThrow(selectInfo).html().contains("Author")) {
+			doc.selectFirstOrThrow(selectInfo).text().substringAfter("Author: ").substringBefore("Art")
+		} else {
+			null
+		}
+
+		manga.copy(
```
Comment (Koitharu) [inline src/main/kotlin/org/koitharu/kotatsu/parsers/site/foolslide/es/SeinagiAdulto.kt:46]: Same

File: src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/all/Manhwa18Cc.kt [hunk 9]
```diff
@@ -0,0 +1,130 @@
...
+			)
+		}
+	}
+
+	override suspend fun getPages(chapter: MangaChapter): List<MangaPage> {
+		val fullUrl = chapter.url.toAbsoluteUrl(domain)
+		val doc = webClient.httpGet(fullUrl).parseHtml()
+		val root = doc.body().selectFirstOrThrow(selectBodyPage)
+		return root.select("img").map { img ->
+			val url = img.src().orEmpty()
```
Comment (Koitharu) [inline src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/all/Manhwa18Cc.kt:120]: I have some doubts about using `orEmpty` for page url, it might be better to throw an exception or skip it

File: src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/en/InstaManhwa.kt [hunk 10]
```diff
@@ -0,0 +1,134 @@
...
+					MangaTag(
+						key = a.attr("href").removeSuffix('/').substringAfterLast('/'),
+						title = a.text().ifEmpty { return@mapNotNullToSet null }.toTitleCase(),
+						source = source,
+					)
+				}.orEmpty(),
+				author = summary?.selectFirst(".mg_author")?.selectFirst("a")?.ownText(),
+				state = when (summary?.selectFirst(".mg_status")?.selectFirst(".summary-content")?.ownText()?.trim()
+					?.lowercase()) {
+					"Ongoing" -> MangaState.ONGOING
```
Comment (Koitharu) [inline src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/en/InstaManhwa.kt:93]: This string will never match because you called `lowercase()` above

File: src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/es/TmoManga.kt [hunk 11]
```diff
@@ -0,0 +1,119 @@
...
+						append("?page=")
+						append(page)
+					}
+				}
+			}
+		}
+		val doc = webClient.httpGet(url).parseHtml()
+
+		return doc.select("div.page-item-detail").map { div ->
+			val href = div.selectFirst("a")?.attrAsRelativeUrlOrNull("href") ?: div.parseFailed("Link not found")
```
Comment (Koitharu) [inline src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/es/TmoManga.kt:68]:
```suggestion
			val href = div.selectFirstOrThrow("a")?.attrAsRelativeUrl("href")
```

File: src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/es/TmoManga.kt [hunk 12]
```diff
@@ -0,0 +1,119 @@
...
+				source = source,
+				isNsfw = isNsfwSource,
+			)
+		}
+	}
+
+	override suspend fun getChapters(manga: Manga, doc: Document): List<MangaChapter> {
+		return doc.body().select(selectChapter).mapChapters(reversed = true) { i, li ->
+			val a = li.selectFirst("a")
+			val href = a?.attrAsRelativeUrlOrNull("href") ?: li.parseFailed("Link is missing")
```
Comment (Koitharu) [inline src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/es/TmoManga.kt:89]:
```suggestion
			val href = a.attrAsRelativeUrl("href")
```

File: src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/es/TmoManga.kt [hunk 13]
```diff
@@ -0,0 +1,119 @@
...
+				state = null,
+				source = source,
+				isNsfw = isNsfwSource,
+			)
+		}
+	}
+
+	override suspend fun getChapters(manga: Manga, doc: Document): List<MangaChapter> {
+		return doc.body().select(selectChapter).mapChapters(reversed = true) { i, li ->
+			val a = li.selectFirst("a")
```
Comment (Koitharu) [inline src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/es/TmoManga.kt:88]:
```suggestion
			val a = li.selectFirstOrThrow("a")
```

File: src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/tr/TitanManga.kt [hunk 14]
```diff
@@ -0,0 +1,37 @@
...
+
+@MangaSourceParser("TITANMANGA", "Titan Manga", "tr")
+internal class TitanManga(context: MangaLoaderContext) :
+	MadaraParser(context, MangaSource.TITANMANGA, "titanmanga.com") {
+
+	override suspend fun loadChapters(mangaUrl: String, document: Document): List<MangaChapter> {
+		val url = mangaUrl.toAbsoluteUrl(domain).removeSuffix('/') + "/ajax/chapters/"
+		val doc = webClient.httpPost(url, emptyMap()).parseHtml()
+		return doc.select(selectChapter).mapChapters(reversed = true) { i, li ->
+			val a = li.selectFirst("a")
```
Comment (Koitharu) [inline src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/tr/TitanManga.kt:21]:
```suggestion
			val a = li.selectFirstOrThrow("a")
```

File: src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/tr/TitanManga.kt [hunk 15]
```diff
@@ -0,0 +1,37 @@
...
+			val href = a?.attrAsRelativeUrlOrNull("href") ?: li.parseFailed("Link is missing")
```
Comment (Koitharu) [inline src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/tr/TitanManga.kt:22]:
```suggestion
			val href = a.attrAsRelativeUrlOrNull("href")
```

File: src/main/kotlin/org/koitharu/kotatsu/parsers/site/madtheme/all/ManhuaScan.kt [hunk 16]
```diff
@@ -0,0 +1,102 @@
...
+	override suspend fun getListPage(
+		page: Int,
+		query: String?,
+		tags: Set<MangaTag>?,
+		sortOrder: SortOrder,
+	): List<Manga> {
+		val url = buildString {
+			append("https://")
+			append(domain)
+			append("/$listUrl?sort=")
```
Comment (Koitharu) [inline src/main/kotlin/org/koitharu/kotatsu/parsers/site/madtheme/all/ManhuaScan.kt:26]:
```suggestion
			append('/')
			append(listUrl)
			append("?sort=")
```

File: src/main/kotlin/org/koitharu/kotatsu/parsers/site/madtheme/all/ManhuaScan.kt [hunk 17]
```diff
@@ -0,0 +1,102 @@
...
+	}
+
+	override suspend fun getPages(chapter: MangaChapter): List<MangaPage> {
+		val chapterUrl = chapter.url.toAbsoluteUrl(domain)
+		val docs = webClient.httpGet(chapterUrl).parseHtml()
+
+		val script = docs.selectFirstOrThrow("script:containsData(var chapImages)")
+		val images = script.data().substringAfter("= \"").substringBefore("\";").split(",")
+
+		val pages = ArrayList<MangaPage>()
```
Comment (Koitharu) [inline src/main/kotlin/org/koitharu/kotatsu/parsers/site/madtheme/all/ManhuaScan.kt:88]:
```suggestion
		return images.map {
			MangaPage(
				id = generateUid(it),
				url = it,
				preview = null,
				source = source,
			)
		}
```

File: src/main/kotlin/org/koitharu/kotatsu/parsers/site/mangareader/en/Constellarcomic.kt [hunk 18]
```diff
@@ -0,0 +1,32 @@
...
+	MangaReaderParser(context, MangaSource.CONSTELLARCOMIC, "constellarcomic.com", pageSize = 30, searchPageSize = 18) {
+	override val selectTestScript = "script:containsData(ts_rea_der_._run)"
+
+	override suspend fun getDetails(manga: Manga): Manga {
+		val docs = webClient.httpGet(manga.url.toAbsoluteUrl(domain)).parseHtml()
+		val chapters = docs.select(selectChapter).mapChapters(reversed = true) { index, element ->
+			val url = element.selectFirst("a")?.attrAsRelativeUrl("href") ?: return@mapChapters null
+			MangaChapter(
+				id = generateUid(url),
+				name = element.selectFirst(".chapternum")?.text() ?: "Chapter ${index + 1}",
```
Comment (Koitharu) [inline src/main/kotlin/org/koitharu/kotatsu/parsers/site/mangareader/en/Constellarcomic.kt:21]:
```suggestion
				name = element.selectFirst(".chapternum")?.textOrNull() ?: "Chapter ${index + 1}",
```

File: src/main/kotlin/org/koitharu/kotatsu/parsers/site/mangareader/es/TuManhwas.kt [hunk 19]
```diff
@@ -0,0 +1,190 @@
...
+	}
+
+	override suspend fun getDetails(manga: Manga): Manga {
+		val docs = webClient.httpGet(manga.url.toAbsoluteUrl(domain)).parseHtml()
+		val dateFormat = SimpleDateFormat(datePattern, sourceLocale)
+		val chapters = docs.select(selectChapter).mapChapters(reversed = true) { index, element ->
+			val url = element.selectFirst("a")?.attrAsRelativeUrl("href") ?: return@mapChapters null
+			MangaChapter(
+				id = generateUid(url),
+				name = element.selectFirst(".chapternum")?.text() ?: "Chapter ${index + 1}",
```
Comment (Koitharu) [inline src/main/kotlin/org/koitharu/kotatsu/parsers/site/mangareader/es/TuManhwas.kt:60]:
```suggestion
				id = generateUid(url),
				name = element.selectFirst(".chapternum")?.textOrNull() ?: "Chapter ${index + 1}",
```

File: src/main/kotlin/org/koitharu/kotatsu/parsers/site/mangareader/es/TuManhwas.kt [hunk 20]
```diff
@@ -0,0 +1,190 @@
...
+	}
+
+	override suspend fun parseInfo(docs: Document, manga: Manga, chapters: List<MangaChapter>): Manga {
+
+		val stateSelect = docs.selectFirst(".tsinfo div:contains(Estado)")
+		val state = stateSelect?.lastElementChild()
+		val mangaState = state?.let {
+			when (it.text()) {
+				"publishing" -> MangaState.ONGOING
+				"Terminado" -> MangaState.FINISHED
```
Comment (Koitharu) [inline src/main/kotlin/org/koitharu/kotatsu/parsers/site/mangareader/es/TuManhwas.kt:82]: Is the first letter in lowercase or uppercase?

File: src/main/kotlin/org/koitharu/kotatsu/parsers/site/mmrcms/ar/Onma.kt [hunk 21]
```diff
@@ -0,0 +1,151 @@
...
+			}
+		}
+
+		val doc = webClient.httpGet(url).parseHtml()
+
+		if (sortOrder == SortOrder.UPDATED) {
+
+			return doc.select("div.manga-item").map { div ->
+				val href = div.selectFirstOrThrow("a").attrAsRelativeUrl("href")
+				val deeplink = href.substringAfterLast("/")
```
Comment (Koitharu) [inline src/main/kotlin/org/koitharu/kotatsu/parsers/site/mmrcms/ar/Onma.kt:75]:
```suggestion
				val deeplink = href.substringAfterLast('/')
```

**Comment by Koitharu** [comment]
Btw I granted you write access to this repository so you can create branches at it directly if you want)

**Comment by davvarrr** [comment]
> Btw I granted you write access to this repository so you can create branches at it directly if you want)

I don't really want to break things so I prefer to submit de pr for the moment ;)

**Comment by Koitharu** [comment]
I mean you can create your branch in this repository and make PR from it. In this case I will be able to commit to this branch too

**Comment by davvarrr** [comment]
Ok I'll look at it next time I add something ;)
