### PR TITLE
add sources and fix

### LINKED ISSUE #4: [Source Request] MangaLife
Website: https://manga4life.com/
Language: English

Will look forward on this manga reader from now! ♥️

### LINKED ISSUE #26: [Site Request] ComicCastle
### Source name

comicastle

### Source link

https://comicastle.org/home

### Language

English

### Other details

Comicastle is a website which has many comics (eg. Marvel,DC,etc) and has a nice library.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have updated the app to version **[3.3.1](https://github.com/KotatsuApp/Kotatsu/releases/latest)**.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #34: [Site Request] ComicExtra
### Source name

comicextra

### Source link

https://www.comicextra.com

### Language

English

### Other details

ComicExtra is a website which has many comics (eg. Marvel,DC,etc) and has a nice library.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have updated the app to version **[3.3.1](https://github.com/KotatsuApp/Kotatsu/releases/latest)**.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #103: Otakusan source
### Source name

Otakusan

### Source link

https://otakusan.net/

### Language

Vietnamese

### Other details

Another Vietnamese source, I hope this one will appear soon

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

### LINKED ISSUE #211: JapScan Cannot decode page list
### Source information

JapScan

### Steps to reproduce

Read a chapter

### Kotatsu version

5.3.4

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

### PR DESCRIPTION
**Pull request by davvarrr**
fix 
RealmScans 

change domain 
Manga Starz

remove :
 japscan -> close #211 // to be added to the list of unmaintained sources
thesugarscan.com
limascans.xyz
todaymic.com
mangakio.me

Add sources :

www.archerscans.com
manga4life.com -> close #4 
arkhamscan.com
mangagreat.org
asurascans.us
bananamanga.net
www.brmangas.net
mangaflame.org
coffeemanga.top
comicastle.org > close #26
comicextra.net -> close #34
www.comicscans.org
www.elitemanga.org
factmanga.com
glmanga.com
www.gufengmh.com
www.imitui.com
www.kings-manga.co
komikgue.pro
luffymanga.com
manga18h.com
manga18x.net
manga-1001.com
mangabee.net
mangaclash.tv
mangacrazy.net
mangadop.net
mangakakalot.io
mangakitsu.com
manganelo.biz
manganelo.website
manganerds.com
mangaryu.com
mangaruby.com
mangaowl.io
mangaonline.team
mangarose.net
mangaowl.one
mangaowl.us
mangapure.net
mangarock.team
mangaqueen.com
mangaqueen.online
manhwas.com
mangatop.site
myrockmanga.com
opscans.com
www.nekopost.co
mangatx.gg
onlymanhwa.org
noromax.my.id
manhwanew.com
mangatyrant.com
monomanga.com
myrockmanga.com
manhuadex.com
manhwamanhua.com
manhwahentai.to
manhuamanhwa.online
manhuazonghe.com
manhwa2read.com
otakusan.net ( en )-> close #103
otakusan.net ( vi )
pawmanga.com
ponymanga.com
potatomanga.xyz
1stkiss-manga.com
1stkissmanga.tv
1stmanhwa.com
toonizy.com
webdexscans.com
webtooncity.com
zinmanga.top

### CODE REVIEW

File: src/main/kotlin/org/koitharu/kotatsu/parsers/site/en/ComicExtra.kt [hunk 1]
```diff
@@ -0,0 +1,151 @@
...
+			)
+		}
+	}
+
+
+	override suspend fun getTags(): Set<MangaTag> {
+		val doc = webClient.httpGet("https://$domain/popular-comic").parseHtml()
+		return doc.select("li.tag-item a").mapNotNullToSet { a ->
+			MangaTag(
+				key = a.attr("href").substringAfterLast("/"),
```
Comment (Koitharu) [inline src/main/kotlin/org/koitharu/kotatsu/parsers/site/en/ComicExtra.kt:89]:
```suggestion
				key = a.attr("href").substringAfterLast('/'),
```

File: src/main/kotlin/org/koitharu/kotatsu/parsers/site/en/ComicExtra.kt [hunk 2]
```diff
@@ -0,0 +1,151 @@
...
+
+					val a = tr.selectFirstOrThrow("a")
+					val url = a.attrAsRelativeUrl("href") + "/full"
+					val name = a.text()
+					val dateText = tr.select("td").last()?.text()
+					val dateFormat = SimpleDateFormat("MM/dd/yy", sourceLocale)
+					MangaChapter(
+						id = generateUid(url),
+						name = name,
+						number = i,
```
Comment (Koitharu) [inline src/main/kotlin/org/koitharu/kotatsu/parsers/site/en/ComicExtra.kt:125]:
```suggestion
						number = i + 1,
```

File: src/main/kotlin/org/koitharu/kotatsu/parsers/site/en/ComicExtra.kt [hunk 3]
```diff
@@ -0,0 +1,151 @@
...
+			author = doc.select("dt.movie-dt:contains(Author:) + dd").text(),
+			description = doc.getElementById("film-content")?.text(),
+			chapters = doc.requireElementById("list").select("tr")
+				.mapChapters(reversed = true) { i, tr ->
+
+					val a = tr.selectFirstOrThrow("a")
+					val url = a.attrAsRelativeUrl("href") + "/full"
+					val name = a.text()
+					val dateText = tr.select("td").last()?.text()
+					val dateFormat = SimpleDateFormat("MM/dd/yy", sourceLocale)
```
Comment (Koitharu) [inline src/main/kotlin/org/koitharu/kotatsu/parsers/site/en/ComicExtra.kt:121]: There are no reason to create new `SimpleDateFormat` instance every time, it might be better to move this line out of the `mapChapters` lambda

File: src/main/kotlin/org/koitharu/kotatsu/parsers/site/en/Comicastle.kt [hunk 4]
```diff
@@ -0,0 +1,161 @@
...
+			description = root.getElementById("comic-desc")?.text(),
+			chapters = root.select("div.card-body > .table-responsive tr a")
+				.mapChapters { i, a ->
+
+					val url = a.attrAsRelativeUrl("href")
+					val name = a.text()
+					MangaChapter(
+						id = generateUid(url),
+						name = name,
+						number = i,
```
Comment (Koitharu) [inline src/main/kotlin/org/koitharu/kotatsu/parsers/site/en/Comicastle.kt:135]:
```suggestion
						number = i + 1,
```

File: src/main/kotlin/org/koitharu/kotatsu/parsers/site/fr/JapScanParser.kt
Comment (Koitharu) [inline src/main/kotlin/org/koitharu/kotatsu/parsers/site/fr/JapScanParser.kt:1]: It might be better to remove `@MangaSourceParser` annotation from this class but keep it for the future

File: src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/en/CoffeeMangaTop.kt [hunk 5]
```diff
@@ -0,0 +1,143 @@
...
+				scanlator = null,
+				source = source,
+			)
+		}
+	}
+
+	override suspend fun getPages(chapter: MangaChapter): List<MangaPage> {
+		val fullUrl = chapter.url.toAbsoluteUrl(domain)
+		val doc = webClient.httpGet(fullUrl).parseHtml()
+		val urlarray = doc.select("p#arraydata").text().split(",").toTypedArray()
```
Comment (Koitharu) [inline src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/en/CoffeeMangaTop.kt:133]:
```suggestion
		val urlarray = doc.select("p#arraydata").text().split(',').toTypedArray()
```

File: src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/en/MangaPure.kt [hunk 6]
```diff
@@ -0,0 +1,145 @@
...
+					MangaTag(
+						key = a.attr("href").removeSuffix('/').substringAfterLast('/'),
+						title = a.text().ifEmpty { return@mapNotNullToSet null }.toTitleCase(),
+						source = source,
+					)
+				}.orEmpty(),
+				author = summary?.selectFirst(".mg_author")?.selectFirst("a")?.ownText(),
+				state = when (summary?.selectFirst(".mg_status")?.selectFirst(".summary-content")?.ownText()?.trim()
+					?.lowercase()) {
+					"Ongoing" -> MangaState.ONGOING
```
Comment (Koitharu) [inline src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/en/MangaPure.kt:93]:
```suggestion
					"ongoing" -> MangaState.ONGOING
```

You called `.lowercase` line ago, right?)

File: src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/en/MangaPure.kt [hunk 7]
```diff
@@ -0,0 +1,145 @@
...
+					"Completed " -> MangaState.FINISHED
```
Comment (Koitharu) [inline src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/en/MangaPure.kt:94]:
```suggestion
					"completed " -> MangaState.FINISHED
```

File: src/main/kotlin/org/koitharu/kotatsu/parsers/site/mangareader/en/RealmScans.kt [hunk 8]
```diff
@@ -1,15 +1,94 @@
...
+	}
+
+	override suspend fun parseInfo(docs: Document, manga: Manga, chapters: List<MangaChapter>): Manga {
+		val tagMap = getOrCreateTagMap()
+		val selectTag = docs.select(".wd-full .mgen > a")
+		val tags = selectTag.mapNotNullToSet { tagMap[it.text()] }
+		val mangaState = docs.selectFirst(".bs-status")?.let {
+			when (it.text()) {
+				"ongoing" -> MangaState.ONGOING
+				"Completed" -> MangaState.FINISHED
```
Comment (Koitharu) [inline src/main/kotlin/org/koitharu/kotatsu/parsers/site/mangareader/en/RealmScans.kt:73]: comparison is case-sensitive, right?

File: src/main/kotlin/org/koitharu/kotatsu/parsers/site/pt/BrMangas.kt [hunk 9]
```diff
@@ -0,0 +1,145 @@
...
+				source = source,
+			)
+		}
+	}
+
+	override suspend fun getTags(): Set<MangaTag> {
+		val doc = webClient.httpGet("https://$domain/lista-de-generos-de-manga/").parseHtml()
+		return doc.select(".genres_page a").mapNotNullToSet { a ->
+			MangaTag(
+				key = a.attr("href").removeSuffix("/").substringAfterLast("/"),
```
Comment (Koitharu) [inline src/main/kotlin/org/koitharu/kotatsu/parsers/site/pt/BrMangas.kt:89]:
```suggestion
				key = a.attr("href").removeSuffix('/').substringAfterLast('/'),
```

File: src/main/kotlin/org/koitharu/kotatsu/parsers/site/pt/BrMangas.kt [hunk 10]
```diff
@@ -0,0 +1,145 @@
...
+	}
+
+	override suspend fun getDetails(manga: Manga): Manga {
+		val doc = webClient.httpGet(manga.url.toAbsoluteUrl(domain)).parseHtml()
+		return manga.copy(
+			altTitle = null,
+			state = null,
+			tags = doc.select("div.serie-infos li:contains(Categorias:) a").mapNotNullToSet { a ->
+				MangaTag(
+					key = a.attr("href").removeSuffix("/").substringAfterLast("/"),
```
Comment (Koitharu) [inline src/main/kotlin/org/koitharu/kotatsu/parsers/site/pt/BrMangas.kt:103]:
```suggestion
					key = a.attr("href").removeSuffix('/').substringAfterLast('/'),
```

File: src/main/kotlin/org/koitharu/kotatsu/parsers/site/pt/BrMangas.kt [hunk 11]
```diff
@@ -0,0 +1,145 @@
...
+			description = doc.select(".serie-texto p").text(),
+			isNsfw = doc.select("div.serie-infos li:contains(Categorias:)").text().contains("Hentai"),
+			chapters = doc.select(".capitulos li a")
+				.mapChapters(reversed = true) { i, a ->
+					val url = a.attrAsRelativeUrl("href")
+					val name = a.text()
+					MangaChapter(
+						id = generateUid(url),
+						name = name,
+						number = i,
```
Comment (Koitharu) [inline src/main/kotlin/org/koitharu/kotatsu/parsers/site/pt/BrMangas.kt:118]:
```suggestion
						number = i + 1,
```

File: src/main/kotlin/org/koitharu/kotatsu/parsers/site/pt/BrMangas.kt [hunk 12]
```diff
@@ -0,0 +1,145 @@
...
+					)
+				},
+		)
+	}
+
+	override suspend fun getPages(chapter: MangaChapter): List<MangaPage> {
+		val fullUrl = chapter.url.toAbsoluteUrl(domain)
+		val doc = webClient.httpGet(fullUrl).parseHtml()
+		val scriptData =
+			doc.selectFirstOrThrow("script:containsData(imageArray)").data().substringAfter("[").substringBefore("]")
```
Comment (Koitharu) [inline src/main/kotlin/org/koitharu/kotatsu/parsers/site/pt/BrMangas.kt:133]:
```suggestion
			doc.selectFirstOrThrow("script:containsData(imageArray)").data().substringAfter('[').substringBefore(']')
```

File: src/main/kotlin/org/koitharu/kotatsu/parsers/site/sinmh/SinmhParser.kt [hunk 13]
```diff
@@ -0,0 +1,203 @@
...
+				source = source,
+				isNsfw = isNsfwSource,
+			)
+		}
+	}
+
+	override suspend fun getTags(): Set<MangaTag> {
+		val doc = webClient.httpGet("https://$domain/$listUrl").parseHtml()
+		return doc.select(".filter-item:contains(按剧情) li a:not(.active)").mapNotNullToSet { a ->
+			val href = a.attr("href").removeSuffix("/").substringAfterLast("/")
```
Comment (Koitharu) [inline src/main/kotlin/org/koitharu/kotatsu/parsers/site/sinmh/SinmhParser.kt:107]:
```suggestion
			val href = a.attr("href").removeSuffix('/').substringAfterLast('/')
```

File: src/main/kotlin/org/koitharu/kotatsu/parsers/site/sinmh/SinmhParser.kt [hunk 14]
```diff
@@ -0,0 +1,203 @@
...
+			chapters = chapters,
+		)
+	}
+
+
+	protected open val selectChapter = "ul#chapter-list-1 li"
+
+	protected open suspend fun getChapters(manga: Manga, doc: Document): List<MangaChapter> {
+		return doc.body().select(selectChapter).mapChapters { i, li ->
+			val href = li.selectFirstOrThrow("a").attrAsRelativeUrlOrNull("href") ?: li.parseFailed("Link is missing")
```
Comment (Koitharu) [inline src/main/kotlin/org/koitharu/kotatsu/parsers/site/sinmh/SinmhParser.kt:155]:
```suggestion
			val href = li.selectFirstOrThrow("a").attrAsRelativeUrl("href")
```

**Comment by davvarrr** [comment]
the changes were made thanks for the corrections.
For manga4life I'm not sure that json sorting is optimal (I still have trouble working on json)
and I did not find a simple solution to sort the JSON to create the Updated options I do not know if you had a solution (the date and in each manga ex j[0][lt] => 1610161702, )

File: src/main/kotlin/org/koitharu/kotatsu/parsers/site/fr/JapScanParser.kt
Comment (davvarrr) [reply src/main/kotlin/org/koitharu/kotatsu/parsers/site/fr/JapScanParser.kt:1]: for japscan I'd let you add it but I don't think it's useful to leave a source that you know can never be added.
